### ISSUE TITLE
Why not use /etc/environment for Linux?

### ISSUE THREAD

**Issue by decibelhertz** [GeoffWilliams/environment_variable#1]
Example at http://www.thesysadminhimself.com/2013/08/configuring-web-proxy-on-centos.html

Works for me, for Debian and RedHat variants.  In this way, CSH users should get the same environmental settings as BASH users, etc.

Borrowing from your class, here's what I did.  Feel free to borrow back (or not).
```puppet
# Manage an environment variable. Should only be called
# by profile::environment
define profile::envvar(
  $value,
  String                   $variable = $title,
  Enum['present','absent'] $ensure   = present,
) {

  $_value = is_array($value) ? {
    true    => join($value,','),
    default => $value,
  }

  case $::osfamily {
    'Debian','RedHat': {
      ensure_resource('concat','/etc/environment',{
        owner          => 'root',
        mode           => '0644',
        ensure_newline => true,
        warn           => true,
      })
      concat::fragment { "${variable}=${_value}":
        target  => '/etc/environment',
        content => "${variable}=\"${_value}\"",
      }
    } 'Windows': {
      windows_env { $variable :
        ensure    => $ensure,
        value     => $_value,
        mergemode => 'clobber',
      }
    } default: {
      # NOOP
    }
  }
}
```
Cheers.

**Comment by GeoffWilliams** [comment]
Thinking back to when I wrote this, writing `/etc/environment` like this was not allowed for exactly the reason you mentioned - if there was something already in there that puppet removes it could break big enterprise apps.  Alternatively altering `path` (or `ld_library_path`...) here could also alter the behaviour of these apps.  Since files under `/etc/profile.d` can be created at-will with the contents 100% owned by puppet, this was the right place to create things this time.  There is merit writing `/etc/environment` though, perhaps with a file_line or augeas.  Perhaps If I get time it's worth adding opt-in alteration to `/etc/environment`

**Comment by GeoffWilliams** [comment]
BTW the sample you have above contains a bug I just fixed with setting variables on windows:
https://github.com/GeoffWilliams/environment_variable/commit/521e1d769376e00ab2e837e3edb4c8d3d9a9b44e#diff-fbb93a8f9bc3f9ed0fde61aaf98c57a6R219

**Comment by decibelhertz** [comment]
Noted.  Thanks

**Comment by decibelhertz** [comment]
FWIW https://github.com/nvalentine-puppetlabs/puppet-systemenv/blob/master/manifests/var.pp uses `ini_setting` to achieve what you speak of.  Nice trick, and should allow other resources outside the module to touch the file.
